export const pastData = [
  {
    sn: 1,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    date: "11/16/2023",
    duration: "1 day",
    participant: "10",
    totalCost: "7503.31",
  },
  {
    sn: 2,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    date: "11/16/2023",
    duration: "1 day",
    participant: "10",
    totalCost: "7503.31",
  },
  {
    sn: 3,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    date: "11/16/2023",
    duration: "1 day",
    participant: "10",
    totalCost: "7503.31",
  },
  {
    sn: 4,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    date: "11/16/2023",
    duration: "1 day",
    participant: "10",
    totalCost: "7503.31",
  },
  {
    sn: 5,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    date: "11/16/2023",
    duration: "1 day",
    participant: "10",
    totalCost: "7503.31",
  },
];

export const cancelData = [
  {
    sn: 1,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    checkIn: "11/16/2023",
    checkOut: "9/17/2023",
    roomType: "SYPM",
    cancelDate: "2024-01-24",
    status: "cancelled",
  },
  {
    sn: 2,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    checkIn: "11/16/2023",
    checkOut: "9/17/2023",
    roomType: "SYPM",
    cancelDate: "2024-01-24",
    status: "pending",
  },
  {
    sn: 3,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    checkIn: "11/16/2023",
    checkOut: "9/17/2023",
    roomType: "SYPM",
    cancelDate: "2024-01-24",
    status: "refunded",
  },
  {
    sn: 4,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    checkIn: "11/16/2023",
    checkOut: "9/17/2023",
    roomType: "SYPM",
    cancelDate: "2024-01-24",
    status: "non-refundable",
  },
  {
    sn: 5,
    name: "Paramakatoi Airport",
    destination: "Paramakatoi",
    checkIn: "11/16/2023",
    checkOut: "9/17/2023",
    roomType: "SYPM",
    cancelDate: "2024-01-24",
    status: "cancelled",
  },
];

export const visaData = [
  {
    sn: 1,
    id: "APP-12354",
    date: "2024-01-05",
    country: "Nigerian",
    destination: "Canada",
    consult: "System Generated",
    status: "Pending",
    action: "pending",
  },
  {
    sn: 2,
    id: "APP-12354",
    date: "2024-01-05",
    country: "Nigerian",
    destination: "Canada",
    consult: "System Generated",
    status: "Contacted",
    action: "contacted",
  },
  {
    sn: 3,
    id: "APP-12354",
    date: "2024-01-05",
    country: "Nigerian",
    destination: "Canada",
    consult: "System Generated",
    status: "Invoiced",
    action: "invoiced",
  },
  {
    sn: 4,
    id: "APP-12354",
    date: "2024-01-05",
    country: "Nigerian",
    destination: "Canada",
    consult: "System Generated",
    status: "Kanban board",
    action: "kanban",
  },
  {
    sn: 5,
    id: "APP-12354",
    date: "2024-01-05",
    country: "Nigerian",
    destination: "Canada",
    consult: "System Generated",
    status: "Invoiced",
    action: "invoiced",
  },
];
